### ISSUE TITLE
Invalid json body results in 500 error

### ISSUE THREAD

**Issue by bartkeizer** [crnk-project/crnk-framework#147]
crnk version: 2.2.20171019140632

When passing invalid json into the request body, JsonParseException is thrown in (JsonApiRequestProcessor.java:70) and handled as an 500 error.
I would expect that invalid json results in 400 Bad request.

**Comment by remmeier** [comment]
true, that would have to be handled. Myself I did so far not stumble on it so far as in is in many situtations hard to send non-json contents.

To fix it, ObjectMapper.readValue is called very early and is not covered by the exception mechanism. So implementing an ExceptionMapper does not help. ExceptionHandling takes place in HttpRequestProcessImpl, but ObjectMapper.readValue happens in JsonApiRequestProcessor (on step before). It is not possible to moved out the exception handling to that place from HttpRequestProcessImpl.dispatchRequest. So this use case has to be handled separately in JsonApiRequestProcessor. Meaning a try catch and constructing a proper response.

PR welcome, otherwise I may come to it sometime.

**Comment by bartkeizer** [comment]
Great job guys! Thanks!

**Comment by remmeier** [comment]
2.3.20171118162238
