### ISSUE TITLE
Wrong treatment of missing attributes

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#242]
According to the [docs](http://jsonapi.org/format/#crud-updating-resource-attributes):
> If a request does not include all of the attributes for a resource, the server MUST interpret the missing attributes as if they were included with their current values. The server MUST NOT interpret missing attributes as null values.

which is actually crnk ignores and fills them with nulls. As a result, resource contains nulls in case of missing attributes -> values go to DB or any other place. So this behaviour obviously wrong from specifications perspective.

`ResourcePatch` which is responsible for update action just removes the attributes which aren't in the request. I would like to fix it but not sure since it might be really a breaking change for ones who already use current logic. 

@remmeier any ideas whether it makes sense to fix and how to configure the backwards compatibility?

**Comment by remmeier** [comment]
where it it fail exactly? Looking at it seems correct. It is a two step process where first potential nested structures are merged so that a current a: {b:1} and patch a: {c:2} will result in a{b:1,c:2}. After that it will iterate over all updated attributes and set them on the original resource. attributes not included in the request are never touched on the original resource (setAttributes). But would have to check in detail.

**Comment by vicmosin** [comment]
According to [current implementation](https://github.com/crnk-project/crnk-framework/blob/master/crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/ResourcePatch.java#L93), any attribute which wasn't passed as request payload will be removed from the list of attributes to update. As a result, as soon as resource object get passed to `repository.save(..)` method it only contains the fields which were in original request and the rest are nulls. Which actually means that behaviour defined in specification must be implemented at client-side i.e. in particular `save` implementation:

1. Fetch the resource 

2. Compare with the one got passed to `save`

3. Fill out the missing fields

I made some quick fix but I guess it won't be trivial as we have check for read-only fields.. Meaning as soon as we do not remove missing attribtues from request payload but replace them with existing values the further logic won't allow as to make an update because some of the attributes might be marked as read-only.

**Comment by remmeier** [comment]
could you have a quick look at the committed test case? that is what you would expect?

**Comment by vicmosin** [comment]
Yeah, I think so. Meaning task name comes from existing resource, category - from request. So I would expect kinda [Union](https://en.wikipedia.org/wiki/Union_(set_theory)) where missing in request values aren't ignored but filled out from original resource

**Comment by vicmosin** [comment]
Wait, shouldn't line 503 in your commit go after lines 504/505?

**Comment by remmeier** [comment]
does not matter in this context, there is no copying or something. That taskPatch document gets modified regardless of the order.

**Comment by vicmosin** [comment]
I will make some tests and come back. Thanks for your time

**Comment by suman8285** [comment]
When I call the resources from postman for patch it is doing findone and merge with the resource but the same is not happening when I call from CRNK client. It is replacing with null values apart for the attributes I had passed in payload. Please let me know if anything can be done for the same

**Comment by remmeier** [comment]
@suman8285 ? how does your resource look like? Java does not really know the difference between "undefined" and null, so it will treat a Boolean as null and a boolean as false and set it on the server accordingly. If this is your problem? In this area one possiblity would be to support @JsonInclude (https://github.com/crnk-project/crnk-framework/issues/25), but in this case on the frontend rather than the backend side.

**Comment by suman8285** [comment]
[product.txt](https://github.com/crnk-project/crnk-framework/files/2610107/product.txt)
[ProductRepository.txt](https://github.com/crnk-project/crnk-framework/files/2610109/ProductRepository.txt)
[ProviderClient.txt](https://github.com/crnk-project/crnk-framework/files/2610110/ProviderClient.txt)

Hi, @remmeier thanks for the help, my concerns is around the patch statergy, i have attached a model,Repository and client 

Here when i call below url through postman  with method PATCH and Content-type =application/vnd.api+json
localhost:9091/cos/products/123?fields[product]=embossed-name

with payload as below
{
  "data": {
    "id": "123",
    "type": "product",
    "attributes": {
     "embossed-name": "Tenzing"
    }
  }
}

It does the fins one and on successful findone it will enter save method in repository with merged resource.

But when i call through client it enters findone and on successful findone it will enter save but here instead of merging the data from the request payload with findone it will make all other field which was not in request payload as null.

**Comment by suman8285** [comment]
@remmeier as said above i am doing manual merge is there a way to do from CRNKClient

**Comment by remmeier** [comment]
sorry did not see the last message since the ticket itself was already closed.

how does the client call look like? you may also set io.crnk to DEBUG in the log level. It will print the request body. I still think the empty handling is what you are looking for, but not sure.
