### ISSUE TITLE
Jax-rs integration doesn't work

### ISSUE THREAD

**Issue by belovaf** [crnk-project/crnk-framework#254]
Hello! I'm trying to setup very simple application:
1. tomcat + jersey + weld-servlet (CDI implementation)
2. crnk: core + cdi + rs + jpa
3. Single JPA Entity: `Address`

My Configuration is:
```
@ApplicationPath("/api")
public class CrnkDemoApplication extends Application {
    @Override
    public Set<Object> getSingletons() {
        CrnkFeature crnk = new CrnkFeature();

        JpaModuleConfig config = new JpaModuleConfig();
        SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
        config.addRepository(
                JpaRepositoryConfig.builder(Address.class).build());
        
        JpaModule jpaModule = JpaModule.createServerModule(
                config,
                sessionFactory.createEntityManager(),
                new CdiTransactionRunner());
        
        crnk.addModule(jpaModule);
        return Collections.singleton(crnk);
    }
}
```
But my Entity doesn't exposed with http://localhost:8080/api/address.
Under debugger I find that JsonApiRequestProcessor#process always create empty (null) JsonPath.
What's wrong with my settings?

**Comment by remmeier** [comment]
I looks mostly ok. Can you also add crnk-home to your setup? then you see a directory listing under /api/ of all the resources available?

the one thing that will cause trouble is new CdiTransactionRunner. you should be able to inject with @Inject since crnk-cdi defines it with @ApplicationScoped. 

We may could complement the crnk-example/example-wildfdly with this setup to have an example.

**Comment by remmeier** [comment]
a second issue is `sessionFactory.createEntityManager()`, it would expect a managed entity manager instance that typically is injected with `@PersistenceContext.` But I assume that is not working in your setup?

**Comment by belovaf** [comment]
I run application on pure Tomcat for simplicity, so I don't have container managed `EntityManager`. But `JpaModuleConfig` initialization looks OK. SessionFactory and Session are correctly initialized.
After adding crnk-home with `crnk.addModule(HomeModule.create());` nothing changes.
http://localhost:8080/api/ returns same 404 code.

**Comment by remmeier** [comment]
other JAXRS resourcs are working? CrnkFilter is invoked?

**Comment by belovaf** [comment]
Yes.
1. `CrnkFilter#filter` is invoked.
2. `HttpRequestProcessorImpl#process` is invoked
3. `JsonApiRequestProcessor#process` is invoked
4. `JsonPath jsonPath = (new PathBuilder(resourceRegistry)).build(path);` returns null

**Comment by remmeier** [comment]
and the resourceRegistry is empty I guess? and a bit strange that the home module gives a 404 as well.

HomeModule => setupModule => process would be the other entrypoint for /api/

**Comment by belovaf** [comment]
Yes, `resourceRegistry#getEntry` always returns null.
But when I look on the `resourceRegistry` under debugger, I can see all registered modules (included JPA and Home) in the `resourceRegistry` internal field.

**Comment by remmeier** [comment]
and the parts within resourceRegistry hold entires for your resources?

and those get the HomeModule invoked for /api/?

**Comment by remmeier** [comment]
alternatively we may also quickly upgrade the jersey-example and wildfly-example a bit.

**Comment by belovaf** [comment]
Parts are empty.

It would be great if you make very simple example with JpaModule and jax-rs!

**Comment by remmeier** [comment]
the wildfly/jersey examples have been updated. Adding Hiberante to Jersey could be one next step to match your setup. But in general I guess there will not be much of a suprise as its seems to match what you are doing.

I would check that HomeModule => process what is going on in there. If that one is working, the rest should also follow shortly. Maybe something is mixed up with context paths or something so that all requests get ignored.

**Comment by remmeier** [comment]
@belovaf  do you have your project somewhere on github by chance?
