### ISSUE TITLE
Content-Type response header disappeared

### ISSUE THREAD

**Issue by weaselmetal** [crnk-project/crnk-framework#287]
When I run my app against a current build of master branch, the response header

`Content-Type: application/vnd.api+json;charset=utf-8`

has disappeared. Integration tests of my app all fail now because of that.

**Comment by remmeier** [comment]
with which setup (spring, jaxrs, servlet,...)? I can check. Most likely something missed when implementing the reactive support.

**Comment by weaselmetal** [comment]
Not sure if that answers your question, but we use an adaptation of `io.crnk.servlet.CrnkFilter` to enter the crnk world.

**Comment by weaselmetal** [comment]
Let me also suggest that you start tagging the official releases. I know that it wasn't an issue in the latest official release. But I'd have to find out which status was released for that (ie what's the last commit that was part of this release).

**Comment by remmeier** [comment]
thx that helps or rather was the suspected setup because there is now also a AsyncCrnkServlet (but still very experimental)

some kind of tagging would be good. ideally also a report with all the resolved ticket, etc. The basics are in place. The release version contains the git commit timestamp. As such it is also quite easy to manually check what is in a release or what not. And the documentation should be automatically published to crnk.io. Not sure whether there is already a Gradle plugin that does all that.

**Comment by weaselmetal** [comment]
Well, it's never impossible to figure out what the last commit was, but tags are well supported by github too and it makes certain things way easier.

**Comment by remmeier** [comment]
fixed on master, was an issue with the crnk-servlet integration. With 2.6 there is now a test suite shared by all integrations, so hopefully does kind of issues go away.

feel free to open a ticket regarding releases.
