### ISSUE TITLE
Allow define depth while merging resources during PATCH

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#386]
As soon as resource has an object of type `JsonNode` (from jackson) merge operation iterates over the attributes . As a result, all the keys inside that custom field are also compared meaning if I send 
```
{ 
   "id": "1",
   "attributes": {
     "json": "{\"key\": \"value\"}"
   }
}
```
but original resource has json value of `{"key2": "value2"}` the resulted value which will go to storage will be
```
{ 
   "id": "1",
   "attributes": {
     "json": "{\"key\": \"value\", \"key2\": \"value2\"}"
   }
}
```
which it makes no sense as I want to override the existing value. Speicification also says nothing about the depth of the merging. Can we fix that?

**Comment by remmeier** [comment]
what is the concrete use case? since for the most ones I did come across the merging was the desired behavior. Ususally nested object are used to structure the resource rather than being atomic values that can only be patched all/nothing. If a value must be cleared, then it was rather setting it to null to match the PATCH semantic of JSONAPI. 

But something similar to the JPA @Embeddable could be interesting to have at some point to designate the nested object (where merging will take place)

**Comment by vicmosin** [comment]
I described the case in my original post :) 

We have a [JsonNode](https://fasterxml.github.io/jackson-databind/javadoc/2.2.0/com/fasterxml/jackson/databind/JsonNode.html) attribute in POJO/Resource since we allow clients to store custom JSON (and it's not plain string as there are cases when we need to validate it). 

TBH I don't really your point here
> If a value must be cleared, then it was rather setting it to null to match the PATCH semantic of JSONAPI

**Comment by remmeier** [comment]
yes, in this case I guess it would make sense. A new attribute to @JsonApiField maybe? Since for generic JsonNode/ObjectNode both strategy, merging or not, are valid depending on the use case I guess.

**Comment by vicmosin** [comment]
What would be the name ?

**Comment by remmeier** [comment]
maybe @JsonApiField.patchStrategy with an enum PatchStrategy having values DEFAULT, MERGE, SET?

**Comment by vicmosin** [comment]
Ok, will try locally first and prepare PR
