### ISSUE TITLE
Append custom query to query spec

### ISSUE THREAD

**Issue by joshjs1991** [crnk-project/crnk-framework#397]
We require sorting by a calculated value while also using querySpec.

The scenario is this:
 - have a list of stores with latitude and longitude
- we want to search for stores and order them by distance from a given longitude and latitude 

Right now we provide a native query but that means we have lost the translation functionality from querySpec to jpaQuery

This is our native query:

```
select s from store s order by 6371 * acos("
                    + "   cos(RADIANS((:latitude))) * cos(RADIANS(s.latitude))"
                    + " * cos(RADIANS(s.longitude) - RADIANS((:longitude)))"
                    + " + sin(RADIANS((:latitude))) * sin(RADIANS(s.latitude))) ASC

```

Is it possible/how can we combine native query and query spec?

**Comment by remmeier** [comment]
there are two possiblities:

1. http://www.crnk.io/releases/latest/documentation/#_customizing_the_jpa_repository to just add the custom criteria expressions. Most likely with JpaCriteriaRepositoryFilter  (since crnk 2.9, not yet on jcenter).

2. http://www.crnk.io/releases/stable/documentation/#_dto_mapping to make "distance" a field on the store resource and allow it to be displayed, sorted, filtered, etc.

**Comment by remmeier** [comment]
reopen if there are more questions

**Comment by rehab-reda0** [comment]
I am having the same question I want to modify the query in the find all want to add having and group b and use aggregate function like concat how I can do so ?
