### ISSUE TITLE
How to get a current user with findAll ? 

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#40]
from @loickR

In a rest api, we basically can manage : http://@host:8080/api/users/me, in order to get the current user session.

I'm working to get this user with a QueryParams : http://@host:8080/api/users?filter[login]="me" but that's going to return a list with one element (or an empty list).

Does another way exist in order to get a current user ?

**Comment by vicmosin** [comment]
I believe the use-case described here is too private and will require too much effort to refactor existing repository approach. One possible solution might be changing `findAll` signature to use some abstract resource object as a generic instead of explicit `ResourceList` i.e. 
`<T extends AbstractResource> T findAll(..)` but still not sure about it..

Nevertheless in my project we also had the same issue so we implemented it manually i.e. by providing an extra-endpoint responds with custom object copying json-api's object structure.
