### ISSUE TITLE
Looking for SpringBoot + JAX-RS integration Example

### ISSUE THREAD

**Issue by mpzarde** [crnk-project/crnk-framework#465]
Hello, thanks for the great framework, looking forward to using it extensively.

I have a SpringBoot (2.1.2) + JPA + crnk (2.11.20190113153635) proof of concept app up and running, no issues there, works great.

But now I'm curious as to how or what the best practice would be to add simple REST (JAX-RS?) methods while maintaining JSONAPI compatibility.

i.e. I have a `CartResourceRepository extends JpaEntityRepositoryBase<CartEntity, Integer>` and all the base operations work great, but what if I just wanted to calculate the value of the cart similar to `public Double calculate(CartEntity cart) {...return Double.valueOf(result);} `as an example? 

Section 3.5.4 of the documentation mentions that repositories can be setup to host both JSONAPI and JAX-RS methods but I'm not even sure that's what I want and honestly I haven't managed to get a calculate method working. Added jersey dependency, added `@Path("carts")
@Produces(HttpHeaders.JSONAPI_CONTENT_TYPE)` to my CartResourceRepository along with `@GET and @Path` but haven't been able to figure out how to configure this or what the ideal pattern would be anyways.

I come from a jax-ws background where I'm used to coding all my @WebMethods manually, this is a bit new to me.

Advice or example appreciated.

Thank you!

**Comment by mpzarde** [comment]
Sorry, my question isn't valid or applicable, I am learning a new (to me) paradigm.

JSONAPI just doesn't do that kind of thing, pretty much the only way to do what I'm describing that's copacetic with JSOANAPI would be to defined an entity or resource such as CalculationResult and defined a relationship such that /carts/1/calcresults would trigger and return a result entity.

Not sure we'd want to do that but here we are, please correct me if I'm wrong in my understanding, looking to learn.

**Comment by remmeier** [comment]
any spring bean implementing resource repository will work. and any additional method annotated should works as well, completld independent. but in general it should be avoided. many things can also be modelled as resouces and relationships and will en up looking cleaner as well.

**Comment by mpzarde** [comment]
Hi, thanks for the reply, I tried the following repository for example

`@Path("umcodes")
@Produces(HttpHeaders.JSONAPI_CONTENT_TYPE)
@Component
public class UmCodeResourceRepository extends JpaEntityRepositoryBase<UmCode, Integer> {
    public UmCodeResourceRepository() {
        super(UmCode.class);
    }

    @GET
    @Path("{id}/calculate")
    public String calculate(@PathParam("id") Integer id) {
        return "stuff";
    }
}`

UmCode is an annotated Crnk JsonApiResource of type "umcodes".

The regular Crnk URLs such as /umcodes or /umcodes/1 work no problem but /umcodes/1/calculate would always end up in a 404 (io.crnk.core.exception.BadRequestException: field not found: calculate), I'm guessing there's a path conflict and I have to annotate the @Path to have a different path than the default crank one?

**Comment by remmeier** [comment]
it is a bit intricate to have know how to set it up, a did not lately do anything with JAXRS and Spring Boot and as such do not have such as setup. But it is well possible.

there are two main paths:

- choose a different content type for the actions; something that passes by  JsonApiRequestProcessor.isJsonApiRequest without triggering it. That is the simple solution, but not necessarly desired.
- make Crnk reognize those JAX-RS methods as "action". From Spring Boot by default you have a Servlet-based AutoConfiguration from CrnkCoreAutoConfiguration. As of yet there is no JAXRS-based AutoConfiguration that is used instead in the presence of JAXRS. It would then make use of CrnkFeature rather than CrnkServlet. 

but if you interested in the JAXRS + Spring Boot setup, maybe it would be best to setup an official AutoConfiguration and add an example to crnk-integration-examples. If you already have some small running snippets, a PR to get that started would be appreciated.

The hacky way would to take some elements out of CrnkFeature added to the current servlet-based setup, like:

```
boot.getCoreModule().setDefaultRepositoryInformationProvider(new JaxrsModule.JaxrsResourceRepositoryInformationProvider());
```

It can be embedded through a CrnkBootConfigurer Spring bean. That is the part  responsible for detecting "actions". But you may also want the JSON:API exception handling.
