### ISSUE TITLE
generic pagination support page[xy] next to offset/limit

### ISSUE THREAD

**Issue by mohlek** [crnk-project/crnk-framework#47]
Is there a reason `QuerySpec` doesn't support `page[number]`?

from the spec:
Note: JSON API is agnostic about the pagination strategy used by a server. Effective pagination strategies include (but are not limited to): page-based, offset-based, and cursor-based. The page query parameter can be used as a basis for any of these strategies. For example, a page-based strategy might use query parameters such as page[number] and page[size], an offset-based strategy might use page[offset] and page[limit], while a cursor-based strategy might use page[cursor].

**Comment by remmeier** [comment]
no reason except time. at some point @ramblur started working on this in the katharsis repo.

**Comment by remmeier** [comment]
could look like;

- new PagingSpec in QuerySpec with <T> QuerySpec.getPaging(T)
- OffsetLimitPagingSpec default implementation
- PagingStrategy interface that abstracts previous/next/... computation
- OffsetLimitPagingStrategy default implementation
- QuerySpecSerializer can lookup PagingStrategy (with a match(...) method to check whether a given strategy can process the request).
- Module/ServiceLocator can contribute new PagingStrategy

**Comment by vicmosin** [comment]
@remmeier Anyone started to work on this?

**Comment by remmeier** [comment]
not so far

**Comment by remmeier** [comment]
if anybody wants to have a look at that, you can let me know

**Comment by vicmosin** [comment]
I guess I will do.. But a bit later, maybe at weekend

**Comment by remmeier** [comment]
would be great if you have time, i can help out as well

**Comment by vicmosin** [comment]
@remmeier I prepared some simple PoC at https://github.com/vicmosin/crnk-framework/tree/issues/47
Let me know if the direction is right. Not sure I will have time tomorrow, so you can continue. Otherwise will do it later, during the week.
Main changes:

- `PagingSpec` interface and its default implementation `OffsetLimitPagingSpec`: define particular paging strategy including paging data (i.e. limit/offset vars) and actual first/next/prev/last links generation
- `OffsetLimitPagingSpec` interface and its default implementation `OffsetLimitPagingSpecDeserializer`: provide abstraction for data deserialization for each `PagingSpec` strategy

It's obvious missing serializer and some tests are failing. But had no enough time today.

**Comment by remmeier** [comment]
can you open up a PR? then we can make use of that review functionality.

will not be around tomorrow as well.

**Comment by Ramblurr** [comment]
Not sure how far crnk has diverged from Katharsis on this front, but I have some old unfinished code on this front here: https://github.com/Cropster/katharsis-framework/commit/39f87621bb151927d52be822fa8c1e1748d0178b

Eventually when we get around to migrating from our patched katharsis version to crnk, we will need this. Not sure when that will be though.

**Comment by remmeier** [comment]
just yesterday it was merged thanks to the PR of @vicmosin. I will also to some experiments with it and then do a release.

crnk API is still fairly compatible, altough QueryParams and some other things have been deprecated. The internal implementation is mostly rewritten (taking Katharsis 2.x as baseline).

**Comment by Ramblurr** [comment]
Mega  props, thanks @vicmosin  and @remmeier  :D That is such good news to hear :)

**Comment by nicolabeghin** [comment]
Hi would it be possible to have an example of how to apply such custom pagination to a given `CrnkClient`/resource?
