### ISSUE TITLE
NullPointerException when using the [LIKE] filter operator

### ISSUE THREAD

**Issue by Jeromesciortino** [crnk-project/crnk-framework#478]
Whenever we are filtering using the LIKE filter operator and the values from the datasource are null, crnk throws a `NullPointerException`.

Example:

Let's say we have a Person resource that has an optional field middleName.  Since this field is optional, its value can be null in the database. If we try to get all persons, with a filter on the middle name such as filter[middleName][LIKE]=%john%, crnk throws a null pointer exception.  From further investigation, it was identified that the cause of this exception is line 61 in the [FilterOperator.java](https://github.com/crnk-project/crnk-framework/blob/master/crnk-core/src/main/java/io/crnk/core/queryspec/FilterOperator.java) class, since variable **value1** had a null value (since the corresponding value inside the database is null).

**Comment by remmeier** [comment]
yes, that check is wrong, it should actually check for `value1` being null. `value` is the pattern, so that one should never be null. In the progress it would also be worthwhile to give those two variables a reasonable name. For all the other FilterOperator implementations, it does not really matter since they are symmetric, but in this case they are not.

**Comment by remmeier** [comment]
fixed on latest repository http://www.crnk.io/releases/latest/

**Comment by Koshux** [comment]
Curiously, do you know when this fix will be published?

**Comment by remmeier** [comment]
http://www.crnk.io/releases/v3.0/ to be available on jcenter tomorrow. some of the new artifacts first need initial approval

**Comment by Koshux** [comment]
@remmeier - Curiously, what was the specific reason for releasing the fix on mavenLatest and not the maven stable version (https://bintray.com/crnk-project/maven/crnk-core)?  The reason I ask is due to the fact that we do not use the unstable & BETA versions.  

Unfortunately due to this, there are several fixes missing from the stable version which we need and cannot use :(

**Comment by remmeier** [comment]
how do you mean? the fix got committed to master and is now available both on the latest and the new beta release. 

In general there is nothing wrong with stability in 3.0-BETA. The only reason for it being BETA is that further cleanup will follow and we don't want to do a 4.0 in a weeks time.

**Comment by Koshux** [comment]
Excuse me if my explanation was a bit vague.  Basically the release that solved this specific issue was released to the non-stable version (2.11.X) but was not released on the stable version.  

I understand that using the new version introduces some new features however at this point we only sought the version which fixed this **LIKE Filter** issue.  Unfortunately the version for this specific fix does not seem to be released on the stable version which left us no choice but to take the 3.0.X version.  Does this help clarify things?

**Comment by remmeier** [comment]
yes, currently only 3.0.X is on jcenter. Today I created a stable_v2 branch. So if there is an issue,  that is releasable as well.
