### ISSUE TITLE
404 Not Found due to filter propagation on related resources

### ISSUE THREAD

**Issue by aawaken** [crnk-project/crnk-framework#520]
Hello,

I have resources A, B, C with bidirectional relationships: A <-> B, A <-> C, all SerializeType.EAGER

I request for resources A, which have B.id = b and C.id = c like that:
host:port/api/resourceA?filter[hasB.id]=b&filter[hasC.id]=c

The repository of A I've implemented as follows:
```

    @Override
    public ResourceList<A> findAll(final QuerySpec querySpec) {
        List<A> resources = myDbService.getResourceList();
        DefaultResourceList<A> results = new DefaultResourceList<>(new ArrayList<>(), new DefaultHasMoreResourcesMetaInformation(), null);
        querySpec.apply(resources, results);
        return results;
    }

```

The findAll method is called, A1(id=a1) and A2(id=a2) found and filtered in the line "querySpec.apply", so that only A1 fitting the criteria is there. At the response building, crnk resolves transitively all the relationships and throws an Exception 404. It happens, because, after finding A1 (id=a1) and corresponding B1 (id=b) and C1 (id=c), transitively it tries now to fetch for B1 all resources of type A. So it calls repo A again, but, this time, it calls the "findAll" method of A with querySpec having additionally the id of A: B.id=b, C.id=c + A.id=a2. Of course, "querySpec.apply;" filters rightly A2 out again, and it delivers empty collection. This leads to 404 triggered by the IncludeRelationshipLoader.

Which strategy or configuration would you suggest to avoid this error?

I use Crnk 2.11

Thank you!

**Comment by remmeier** [comment]
a bit tricky, in general it is recommended to avoid EAGER cyclic relationships. cycles can open up issues like this and the application has to specify the desired behavior how to deal with such situations. If really necessary as in the linked ticket, doing it manually can be an options. there are two others not yet implemented. filtering is done on a per-type basis. So if an inclusion is cyclic and returns the same type of resources, the same filters will be applied. That can be good or bad depending on what the application is doing. There would be two alternatives not yet implemented:

- disable filtering on inclusions alltogether: for many applications it is just no needed, so maybe not worth the complexity to have it by default. IncludeLookupSetter just needs a property equaivalent to INCLUDE_PAGING_ENABLED.

- second strategy would along the lines of http://www.crnk.io/releases/stable/documentation/#_properties => crnk.config.include.behavior but also applied to filters/sorting, not just inclusions. you you can specify sorting by inclusion paths rather than inclusion types. This one would be a bit more effort to support.

**Comment by aawaken** [comment]
Actually, I would prefer a solution, where resources of particular type and id, once filtered out, are not being looked up by it's id again.

What do you think?

**Comment by remmeier** [comment]
not sure. I it can be hard to say what gets filtered and what not because filter can be arbitrary complex. So one may would have to both check both for existence and filtering. This in turn would make an already "dangerous" more complex. Do you need filtering on inclusions? There are valid use cases. But if people start using it more excessively, I usually recommend additional relationships (e.g. DB View-based join tables and things like that). So I'm leaning toward allowing to disable it as a next step. An other question would be whether you really really need the EAGER? Maybe SerializeType.ONLY_ID would be sufficient to break the cycles.

**Comment by aawaken** [comment]
Actually, My use case is the following:
The Client runs POST or PUT on a particular resource A. It may have side effects, so that additional resources (sometimes even having no direct persistent relationships) may be created or updated. The client needs to get this resource together with these transitively changed ones. If any resource was created / changed, the generic repo implementation (common for all repos) recalculates its hashes and marks with a flag every of such resources as changed. The idea was that the repository of A includes the (possibly) affected resources as related ones. The API client needs the hashes and flags the A and related resources.

- So, ONLY_ID would be not sufficient, if we want to omit server round trips.
- If we would use EAGER with inclusion filtering switched off, the resource, previously filtered out, would be still delivered, which would be wrong.

I was also thinking about an alternative: instead of serializing the related resources into synthetic relationships, it could make sense to deliver a type->hash map (or similar) of the affected resources the links information metadata (http://www.crnk.io/releases/v2.11/documentation/#_links_information). How does it sound for you?

**Comment by remmeier** [comment]
sorry for the late reply,missed your post. i thing regular relationships rather than links are still good. i not yet fully grasp all needed in our your use case. I still thing about my previous post of trying to aboid filtering on inclusions. rather have more resources and relationships to have the desired data more naturally from the model.

if somewhere round trip optimizations are on the table, crnk-operations and http2 may help as well.

**Comment by aawaken** [comment]
Hello @remmeier,
thanks for your thoughts.

I try to explain my use case in another way: I need to inform the client about the side effects on other models (interesting props are just type, id and hash, that's why EAGER) on POST / PATCH.

Actual approach: I created many relationships (persistent and not persistent) delivering that models.

Ideally, on POST / PATCH / DELETE the service should deliver only changed models (having special flag set to true). But, I couldn't find better solution rather then EAGERly deliver everything and let client to look through that flags and filter out.

With this approach I have problems:
- POST / PATCH, but also GET: far too many included irrelevant stuff, which gets transitively loaded. I did not see possibility in JSON API to distinguish on transitive delivering of **sub**models between GET, POST and PATCH: In that context, everything is just "GET".
- DELETE: no response possible at all, so the client can not be informed about affected models

So, the *second* idea was to use links. But, *now* I'm thinking about delivering changed models in response metadata. However, the problem of responding on DELETE remains.

Best
Andre

**Comment by remmeier** [comment]
metadata seems like a good idea because it is more related to the update itself rather than the underlying resource. Relationships are then less of a fit. The provided data is then also kind of "transient": only accessible during the update and not available anymore later. An alternative could be a  "Log/ChangeEntry" resource with a queryable repository that allows to search for past changes and all transitive changes caused by this change.

>  in JSON API to distinguish on transitive delivering of submodels between GET, 
> POST and PATCH: In that context, everything is just "GET"

holds for resource-oriented APIs in general. It gives clear boundaries how a model should look like. Sometimes forces you to think twice about a data model, maybe simplify it. But so far at least in my cases it resulted in better, easier to understand models.

**Comment by aawaken** [comment]
Thanks, @remmeier , I  implemented the Metadata solution and moved all EAGER relationships to ONLY_ID, as well as removed all transient relationships. Now the API is much more "slim fit" :-) 

Best
Andre
