### ISSUE TITLE
Return HTTP Status 202 upon creation

### ISSUE THREAD

**Issue by duncanportelli** [crnk-project/crnk-framework#566]
I have a resource which when created is sent to another application to process it. It is queued by the other application and I will not have any visibility of when it is processed. Therefore, I want to send a 202 response back to the user as indicated in the [JSON:API specification](https://jsonapi.org/format/#crud-creating-responses-202).

Is there any way to achieve this using Crnk please?

**Comment by remmeier** [comment]
not yet mentioned in the docs, but there is "HttpStatusBehavior":

`
/**
 * Used to compute HTTP status codes for responses. By default covered by {@link DefaultHttpStatusBehavior}.
 * Applications may register additional status behaviors with
 * {@link io.crnk.core.module.Module.ModuleContext#addHttpStatusBehavior(HttpStatusBehavior)}.
 * The class may implement {@link io.crnk.core.utils.Prioritizable}. The first behavior returning a
 * non-null status code is used.
 * <p>
 * This class is (at least currently) not involved
 * for providing HTTP error status codes, this is done by {@link io.crnk.core.engine.error.ExceptionMapper}.
 */
public interface HttpStatusBehavior {

	/**
	 * @return status code or null if this behavior cannot provide one.
	 */
	Integer getStatus(HttpStatusContext context);

}
`

It is more on the lower layer. Undecided as of yet whether it is sufficient or something higher layer should be offered as well since it is a common use case.
