### ISSUE TITLE
Pass entity to ResourceFilter methods

### ISSUE THREAD

**Issue by weaselmetal** [crnk-project/crnk-framework#571]
It would be helpful if the object being filtered would be passed to the methods of `ResourceFilter`.
This would allow for checks like: is the current user the creator of this object?
... and filter accordingly. Perhaps not way to go for removing entities but I'd need it for field filtering. Means to store the result of a check for the scope of the request would be great too. 
Pseudocode:

```
public FilterBehavior filterField(ResourceField field, HttpMethod method, Object entity) {
  ...
  // handling of field order.creator
  if (getVisibility("order.creator") == null) {
    setVisibility(determineVisibility(entity, "order.creator"));
  }
  return getVisibility("order.creator");
}
  

private FilterBehavior determineVisibility(entity, String attribute) {
  if ("order.creator".equals(attribute) {
    if (currentUser.equals(((Order)entity).creator) {
      return FilterBehavior.NONE;
    } else {
      return FilterBehavior.IGNORE;
    }
  }
}
```

I hope you get the idea.

**Comment by remmeier** [comment]
this kind of limitation was on purpose. Goal was to keep the ResourceFilter independent of the actual data in order to build up the desired data structures of what a user is able to see and change.

Limiting visiblity of data is typically an orthogonal concern I think. It can be handled with the `DataRoomFilter` that can be added to the security filter. The example above fits quite nicely.

**Comment by remmeier** [comment]
updated the documention a bit by referring from one to the other. input welcomed.
