### ISSUE TITLE
ResourceNotFoundException when using @JsonApiExposed(false)

### ISSUE THREAD

**Issue by markuslohn** [crnk-project/crnk-framework#586]
I have configured a nested repository for a JPA based resource. I would like to avoid publishing the endpoint of this nested repository. So I used the annotation @JsonApiExposed(false). So the endpoint is hidden and when testing all available endpoints with SoapUI everything is working as expected. However when I use the crnk client for example to add a "nested" resource with the nested repository the generated URL is wrong and a ResourceNotFoundException is thrown. Instead of generating the URL like `http://servername:port/order-service/order/4711/positions` it generates `http://servername:port/order-service/positions. But this is not available because of the used annotation @JsonApiExposed(false).

**Comment by remmeier** [comment]
will have a look at it on saturyday. should be a quick fix.

**Comment by markuslohn** [comment]
Did you solved this issue?

**Comment by remmeier** [comment]
there is only one place in the system to perform the url computation (ResourceRegistry). But seems like CrnkClient did not fully initialize its underlying resource model leading to wrong URL computation. Fixed the issue and added two tests to `NestedRepositoryClientTest` to verify the urls. With this fix the issue here should resolve itself.
