### ISSUE TITLE
Facet are not sorted by count

### ISSUE THREAD

**Issue by jbmolle** [crnk-project/crnk-framework#645]
Hi,
When I do a facet search, the values are not ordered by value count.
In FacetProviderBase.java, the toList function calls Collections.sort(facetValues); and that works. The returned list is correctly sorted.

But then the list is used in the computeFacet function from FacetRepositoryImpl.java.
There a regular single facet is created and on line 164 we have
facet.setValues(values.stream().collect(Collectors.toMap(FacetValue::getLabel, it -> it)));

The Collectors.toMap will not keep the order of the values.

Maybe using the 4 parameters Collectors.toMap function with LinkedHashMap as 4th parameter will keep insertion order.

Best,
JB

**Comment by remmeier** [comment]
done. note that `labels` is already sorted by the total count. Since the values itself are now sorted as well, it is kind of redudant and could potentially be removed. On the other side having a total order on a map is not something that is given in any framework. So the low-tech flavor of having a seperate `labels` might still proof useful.
