### ISSUE TITLE
QuerySpec currently ignores relations and inclusions

### ISSUE THREAD

**Issue by kacey-lendi** [crnk-project/crnk-framework#655]
Hi,

Based on the documentation, QuerySpec currently ignores relations and inclusions. This means querySpec.apply(resources) does not return any relations or inclusions. How to we get around this for GET requests?

**Comment by remmeier** [comment]
this statement should maybe be clarified. What the documentation meant is that `QuerySpec.apply` will do sorting, filtering and paging. It will not do anything related to inclusion or field sets (but also not necessary since it is in-memory). The crnk engine itself will then be able to do inclusion and filtering, so there is no limitation here, just another place where it happens. For other repositories like JPA it makes very much sense to have this functionality directly in the repository because it allows for optimizations in the database layer.

**Comment by remmeier** [comment]
updated the docs accordingly
